version: '3.8'
services:  
  wuzapi:
    image: g2n/wuzapi:latest
    volumes:
      - wuzapi_dbdata:/app/dbdata
      - wuzapi_files:/app/files
    environment:
      - WUZAPI_ADMIN_TOKEN=VnUtZb9DRnmxPpAUzShBNsUWFH9yywND
      - WUZAPI_ADMIN_USER=Gabriel

    deploy:
      mode: replicated
      replicas: 1
      placement:
          constraints:
            - node.role == manager
      resources:
          limits:
            cpus: '0.5'
            memory: 512M
      labels:
          - traefik.enable=true
          #SSL
          - traefik.http.routers.wuzapi.rule=Host(`wuzapi.g2ngroup.com`)
          - traefik.http.services.wuzapi.loadbalancer.server.port=8080
          - traefik.http.routers.wuzapi.service=wuzapi
          - traefik.http.routers.wuzapi.tls.certresolver=le
          - traefik.http.routers.wuzapi.entrypoints=websecure
          - traefik.http.routers.wuzapi.tls=true
    networks:
        - traefik_public

networks:
  traefik_public:
    external: true

volumes:
  wuzapi_dbdata:
    external: true
  wuzapi_files:
    external: true
